services:
  postgresql_db_autotrack:
    image: postgres:latest
    container_name: postgresql_db_autotrack
    #restart: always
    #Limite de memoria cuando se usa con docker-compose o limitar la memoria cuando se deployea
    #shm_size: 128mb
    ports:
      - 5432:5433
    volumes:
      - postgresql_db_autotrack:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgresdevelop
      POSTGRES_PASSWORD: "123123123"
      PGDATA: /var/lib/postgresql/data
    networks:
      - autotrack_network

volumes:
  postgresql_db_autotrack:


networks:
  autotrack_network:
    driver: bridge
